### ISSUE TITLE
Match package.json engines entry with storeon

### ISSUE THREAD

**Issue by SeinopSys** [distolma/storeon-observable#12]
[storeon's `engines` entry](https://github.com/storeon/storeon/blob/a6c8f08d6847f91020dc464470d0f490ed54cc35/package.json#L68-L70) uses the version constraint below for node:

```
  "engines": {
    "node": ">=10.0.0"
  },
```

Is there any reason why this package doesn't use the same, and if not, could this be changed to match?

**Comment by distolma** [comment]
Fixed in 1.0.1
