### ISSUE TITLE
state$.value returns empty object

### ISSUE THREAD

**Issue by baloghbence0915** [distolma/storeon-observable#60]
Hi Guys,

I have created a short snippet, to describe issue:
https://gist.github.com/baloghbence0915/41a7060bb876b3a0a982f49641811ad3

I continously receive logs like:
`
{}
`
It seems like the value of state observable stuck in the initialization state.

Could you help me on this please?

Thanks in advance,
Bence

**Comment by distolma** [comment]
Hi @baloghbence0915,

I will check this problem soon

**Comment by baloghbence0915** [comment]
Hey @distolma,

Thanks for the answer!

I'm familiar with this way, but it is not luckiest when I want to reach some data from state and then init an API call by that.
(This exmaple is not to full way, how I use epics, just a primitive one, in order to illustrate the root of my problem)

Wouldn't be the purpose to achive this on:
https://github.com/distolma/storeon-observable/blob/master/src/StateObservable.ts#L11-L13

According to this, I suppose the value of '_value' should the latest state that has been dispatched by @changed event. Shouldn't it?
